Development/self update
zirvaorg/client pull request #1
Opened 2024-05-16 01:01 UTC by h22k

2024-05-16 20:22 UTC, sercanarga requested changes

2024-05-16 20:22 UTC, sercanarga commented on helpers/update.go
> +	err = u.runNewPackage("-stealth")
kısa çizgiden(-stealth) oluşan parametreler unix sistemlerde genellikle "-h, -s" gibi tek harfli parametreleri belirtmek için kullanılır.

bizim durumumuzda stealth uzun ve açıklayıcı bir kelime olduğundan dolayı bunu çift kısa çizgi(--stealth) olarak kullanmaya devam etmeliyiz.

2024-05-19 14:33 UTC, sercanarga requested changes

2024-05-19 14:33 UTC, sercanarga commented on cmd/update.go
kullanıcıya göstermek istemediğimiz logları ve yorum satırlarını kaldırabiliriz

2024-05-19 14:33 UTC, sercanarga commented on helpers/update.go
> +const (
update işlevi bir helper function. bu tür constlara sahip olmamalı(buffer size için default değer olabilir). bunlar cmd/update.go içerisinde olmalı ve type ile helper functiona iletilmeli.

2024-05-19 14:33 UTC, sercanarga commented on helpers/update.go
> +type updateHelper struct {
updatehelper için variable dosyanın üstünde kullanılmasına rağmen type tanımı alakasız bir yerde kalmış.

2024-05-19 14:33 UTC, sercanarga commented on helpers/update.go
> +func (u *updateHelper) IsUpToDate(currentVersion string, latest *version.Version) (bool, error) {
```go
IsUpToDate(currentVersion string, latestVersion *version.Version)
```
or
```go
IsUpToDate(current string, latest *version.Version)
```

2024-05-19 14:33 UTC, sercanarga commented on helpers/update.go
> +	fmt.Println(actualChecksum, expectedChecksum, actualChecksum == expectedChecksum)
helper functionlar doğrudan çıktı üretmemeliler

2024-05-19 14:33 UTC, sercanarga commented on helpers/update.go
> +			fmt.Println("Related checksum was found from github")
helper functionlar doğrudan çıktı üretmemeliler

2024-05-19 14:33 UTC, sercanarga commented on helpers/update.go
> +		fmt.Println("Checksum verification failed, downloaded file is deleting now.")
helper functionlar doğrudan çıktı üretmemeliler

2024-05-19 14:33 UTC, sercanarga commented on helpers/update.go
> +	fmt.Printf("Current Process: %d\n", pid)
helper functionlar doğrudan çıktı üretmemeliler

2024-05-19 14:33 UTC, sercanarga commented on helpers/update.go
genel olarak kod karmaşası mevcut, daha anlaşılır hale getirmeliyiz. gerekliyse paketlere bölmeliyiz

2024-05-19 14:33 UTC, sercanarga commented on internal/detect_arch.go
kullanılmayan fonksiyon

2024-05-19 14:33 UTC, sercanarga commented on internal/detect_os.go
> +func FilenameWithExtension(filename string) (string, error) {
bu function detect_os isimli bir dosyanın içerisinde yer almamalı

2024-05-19 14:33 UTC, sercanarga commented on main.go
> +			fmt.Printf("New PID: %d\n", os.Getpid())
debug çıktıları kaldırılmalı

2024-05-23 01:59 UTC, sercanarga commented on internal/checksum.go
> +			return line[0], nil
helper functionlar doğrudan çıktı üretmemeliler

2024-05-23 02:02 UTC, sercanarga commented on internal/checksum.go
> +	latestChecksumFileUriFormat = "https://github.com/zirvaorg/client/releases/download/%s/client_%s_checksums.txt"
latestChecksumFileUriFormat'ı update içerisine taşıyalım

2024-05-23 02:04 UTC, sercanarga commented on helpers/update.go
> +var (
birden çok kez var bloğu tanımlamaya ihtiyaç yok

2024-05-23 02:06 UTC, sercanarga commented on helpers/update.go
> +	tempZipFile := path.Join(tempDir, fmt.Sprintf("%s.%s", "zirva-client", package_url.ZIP_FILE_EXTENSION))
temp file'ın ismini fonksiyonun en üstünde bir sabit olarak tanımlayabiliriz

2024-05-23 02:07 UTC, sercanarga commented on helpers/update.go
> +	if err = os.Chmod(createdFile.Name(), 0777); err != nil {
0777 iznine ihtiyacımız var mı? https://chmod-calculator.com/

2024-05-23 02:09 UTC, sercanarga commented on helpers/update.go
> +func (u *UpdateHelper) notifyString(msg string) {
bu fonksiyonu farklı bir pakete taşıyabiliriz veya mevcut paketin üstlerinde yer alabilir.

2024-05-23 02:21 UTC, sercanarga commented
-update sonrası açılan client ile start komutu beklenildiği gibi çalışmıyor. dizindeki uuid dosyasını okuyamıyor gibi gözüküyor.
-yeni açılan process'e parametre gönderilmesinin önündeki engel aşılmalı.

2024-05-23 19:08 UTC, h22k commented on helpers/update.go
> +	tempZipFile := path.Join(tempDir, fmt.Sprintf("%s.%s", "zirva-client", package_url.ZIP_FILE_EXTENSION))
bunu yapamayiz abi esasen, tempdir degisiyor cunku

2024-05-23 19:09 UTC, h22k commented on helpers/update.go
> +var (
degiskenleri gruplara ayirmak daha mantikli gelmisti bana

2024-05-23 19:30 UTC, h22k commented on helpers/update.go
> +func (u *UpdateHelper) notifyString(msg string) {
bunun nedeni nedir abi?

2024-05-24 01:12 UTC, sercanarga commented on helpers/update.go
> +func (u *UpdateHelper) notifyString(msg string) {
çok arada kalmış. kod karmaşası yaratıyor

2024-05-24 01:13 UTC, sercanarga commented on helpers/update.go
> +	tempZipFile := path.Join(tempDir, fmt.Sprintf("%s.%s", "zirva-client", package_url.ZIP_FILE_EXTENSION))
sadece "zirva-client" kısmını en üstte tanımayalım :)

2024-05-24 01:16 UTC, sercanarga commented on helpers/update.go
> +var (
konsolidasyona zararlı esasında. kod karmaşası yaratıyor

2024-05-25 01:25 UTC, merged